# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\github_repo_jay\MCU-MemTestUtility\gui\Rw-Test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rwTestDialog(object):
    def setupUi(self, rwTestDialog):
        rwTestDialog.setObjectName("rwTestDialog")
        rwTestDialog.resize(353, 208)
        self.label_testSet = QtWidgets.QLabel(rwTestDialog)
        self.label_testSet.setGeometry(QtCore.QRect(20, 20, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_testSet.setFont(font)
        self.label_testSet.setObjectName("label_testSet")
        self.comboBox_testSet = QtWidgets.QComboBox(rwTestDialog)
        self.comboBox_testSet.setGeometry(QtCore.QRect(140, 20, 191, 20))
        self.comboBox_testSet.setObjectName("comboBox_testSet")
        self.comboBox_testSet.addItem("")
        self.pushButton_ok = QtWidgets.QPushButton(rwTestDialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(80, 150, 75, 31))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cancel = QtWidgets.QPushButton(rwTestDialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(210, 150, 75, 31))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_testMemStart = QtWidgets.QLabel(rwTestDialog)
        self.label_testMemStart.setGeometry(QtCore.QRect(20, 50, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_testMemStart.setFont(font)
        self.label_testMemStart.setObjectName("label_testMemStart")
        self.label_testMemSize = QtWidgets.QLabel(rwTestDialog)
        self.label_testMemSize.setGeometry(QtCore.QRect(20, 80, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_testMemSize.setFont(font)
        self.label_testMemSize.setObjectName("label_testMemSize")
        self.label_fillPatternWord = QtWidgets.QLabel(rwTestDialog)
        self.label_fillPatternWord.setGeometry(QtCore.QRect(20, 110, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_fillPatternWord.setFont(font)
        self.label_fillPatternWord.setObjectName("label_fillPatternWord")
        self.lineEdit_testMemSize = QtWidgets.QLineEdit(rwTestDialog)
        self.lineEdit_testMemSize.setGeometry(QtCore.QRect(140, 80, 191, 20))
        self.lineEdit_testMemSize.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_testMemSize.setObjectName("lineEdit_testMemSize")
        self.lineEdit_fillPatternWord = QtWidgets.QLineEdit(rwTestDialog)
        self.lineEdit_fillPatternWord.setGeometry(QtCore.QRect(140, 110, 191, 20))
        self.lineEdit_fillPatternWord.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_fillPatternWord.setObjectName("lineEdit_fillPatternWord")
        self.lineEdit_testMemStart = QtWidgets.QLineEdit(rwTestDialog)
        self.lineEdit_testMemStart.setGeometry(QtCore.QRect(140, 50, 191, 20))
        self.lineEdit_testMemStart.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_testMemStart.setObjectName("lineEdit_testMemStart")

        self.retranslateUi(rwTestDialog)
        QtCore.QMetaObject.connectSlotsByName(rwTestDialog)

    def retranslateUi(self, rwTestDialog):
        _translate = QtCore.QCoreApplication.translate
        rwTestDialog.setWindowTitle(_translate("rwTestDialog", "Dialog"))
        self.label_testSet.setText(_translate("rwTestDialog", "Test Set:"))
        self.comboBox_testSet.setItemText(0, _translate("rwTestDialog", "write-read-verify"))
        self.pushButton_ok.setText(_translate("rwTestDialog", "Ok"))
        self.pushButton_cancel.setText(_translate("rwTestDialog", "Cancel"))
        self.label_testMemStart.setText(_translate("rwTestDialog", "Test MEM start:"))
        self.label_testMemSize.setText(_translate("rwTestDialog", "Test MEM size:"))
        self.label_fillPatternWord.setText(_translate("rwTestDialog", "Fill Pattern Word:"))
        self.lineEdit_testMemSize.setText(_translate("rwTestDialog", "0x80000"))
        self.lineEdit_fillPatternWord.setText(_translate("rwTestDialog", "0x5AA5FF00"))
        self.lineEdit_testMemStart.setText(_translate("rwTestDialog", "0x202c0000"))
